In [1]:
# Standard imports
import numpy as np
import pandas as pd
import plotly.express as plt

url = "https://raw.githubusercontent.com/byuidatascience/data4dwellings/master/data-raw/dwellings_ml/dwellings_ml.csv"

df = pd.read_csv(url)

df.head()

,parcel,abstrprd,livearea,finbsmnt,basement,yrbuilt,totunits,stories,nocars,numbdrm,...,arcstyle_THREE-STORY,arcstyle_TRI-LEVEL,arcstyle_TRI-LEVEL WITH BASEMENT,arcstyle_TWO AND HALF-STORY,arcstyle_TWO-STORY,qualified_Q,qualified_U,status_I,status_V,before1980
0,00102-08-065-065,1130,1346,0,0,2004,1,2,2,2,...,0,0,0,0,0,1,0,1,0,0
1,00102-08-073-073,1130,1249,0,0,2005,1,1,1,2,...,0,0,0,0,0,1,0,1,0,0
2,00102-08-078-078,1130,1346,0,0,2005,1,2,1,2,...,0,0,0,0,0,1,0,1,0,0
3,00102-08-081-081,1130,1146,0,0,2005,1,1,0,2,...,0,0,0,0,0,1,0,1,0,0
4,00102-08-086-086,1130,1249,0,0,2005,1,1,1,2,...,0,0,0,0,0,0,1,1,0,0